export const OCR_PHOTO_TYPES = ['Product Photo','Front Label','Ingredient Label','Nutrition Label','Company / Contact Label','Receipt Photo','Other Evidence Photo','Barcode Photo'];
export const LABEL_PHRASES = ['Bioengineered food','Contains a bioengineered food ingredient','Produced with genetic engineering','Natural flavor','Artificial flavor','Artificial color','Cultured','Fermented','Plant-based','Cell-cultivated','Precision fermented','3D printed','Manufactured using','Distributed by','Imported by'];
const SOURCE_LABELS = { 'Product Photo':'Front label OCR', 'Front Label':'Front label OCR', 'Ingredient Label':'Ingredient label OCR', 'Nutrition Label':'Nutrition label OCR', 'Company / Contact Label':'Company label OCR', 'Receipt Photo':'Receipt OCR', 'Other Evidence Photo':'Evidence photo OCR', 'Barcode Photo':'Evidence photo OCR' };
export function ocrSourceForPhotoType(type){ return SOURCE_LABELS[type] || 'Evidence photo OCR'; }
export function maskSensitiveReceiptText(text='') { return String(text).replace(/\b(?:\d[ -]*?){13,19}\b/g, (m)=>`•••• ${m.replace(/\D/g,'').slice(-4)}`); }
export function splitIngredientsPreservingParentheses(text='') { const out=[]; let cur='', depth=0; for (const ch of String(text)) { if (ch==='(') depth++; if (ch===')' && depth>0) depth--; if (ch===',' && depth===0) { if (cur.trim()) out.push(cur.trim()); cur=''; } else cur+=ch; } if (cur.trim()) out.push(cur.trim()); return out; }
export function parseIngredientLabel(text='') {
  const rawText=String(text||''); const normalized=rawText.replace(/\s+/g,' ').trim(); const warnings=[];
  const ingMatch=normalized.match(/ingredients?\s*[:\-]\s*(.+?)(?=(?:\bcontains\b|\bmay contain\b|\ballergen|\bmanufactured by\b|\bdistributed by\b|\bimported by\b|$))/i);
  const ingredientStatement=(ingMatch?.[1]||'').trim(); if(!ingredientStatement) warnings.push('No clear Ingredients: boundary detected. Review the full OCR text.');
  const allergenStatement=(normalized.match(/\b((?:contains|may contain)[^.;\n]*(?:\.|;|$))/i)?.[1]||'').trim();
  const companyStatement=(normalized.match(/\b((?:manufactured by|distributed by|imported by|licensed by|made for|packed for)[^\n]{0,220})/i)?.[1]||'').trim();
  const ingredientEntries=splitIngredientsPreservingParentheses(ingredientStatement).map((part)=>({ ingredientName:part, originalText:part, normalizedName:part.toLowerCase(), notes:'', status:'Needs research', evidenceIds:[], userReviewed:false }));
  return { rawText, ingredientStatement, allergenStatement, companyStatement, ingredientEntries, warnings };
}
export function detectLabelPhrases(text='') { const lower=String(text).toLowerCase(); return LABEL_PHRASES.filter((p)=>lower.includes(p.toLowerCase())).map((phrase)=>({ phrase, notice:'Label phrase detected. This does not independently verify the product’s manufacturing method, safety, ownership, or regulatory status.' })); }
function firstLine(text){ return String(text).split(/\n|\r/).map(s=>s.trim()).filter(Boolean)[0]||''; }
function match(text, re){ return String(text).match(re)?.[1]?.trim() || ''; }
export function buildOcrSuggestions(photoType, text, product={}) {
  const safeText = photoType==='Receipt Photo' ? maskSensitiveReceiptText(text) : String(text||''); const warnings=[]; const suggestions=[]; const phraseDetections=detectLabelPhrases(safeText);
  const add=(field,label,value)=>{ if(value) suggestions.push({ field,label,value, existingValue: product[field] || '', action: product[field] ? 'keep' : 'replace', selected: !product[field] }); };
  if(['Front Label','Product Photo','Barcode Photo'].includes(photoType)){ add('productName','Product name',firstLine(safeText)); add('brand','Brand',match(safeText,/\b(?:brand)\s*[:\-]\s*([^\n]+)/i)); add('category','Category',match(safeText,/\b(?:category)\s*[:\-]\s*([^\n]+)/i)); add('packagingLabels','Packaging labels / claims',safeText.slice(0,500)); }
  if(photoType==='Ingredient Label'){ const parsed=parseIngredientLabel(safeText); warnings.push(...parsed.warnings); add('ingredientsNotes','Full ingredient statement',parsed.ingredientStatement || safeText); if(parsed.allergenStatement) add('ingredientsNotes','Allergen statement',parsed.allergenStatement); if(parsed.companyStatement) add('userNotes','Manufacturer/distributor text near ingredients',parsed.companyStatement); }
  if(photoType==='Nutrition Label'){ add('nutritionNotes','Nutrition notes',safeText); add('nutritionNotes','Serving size',match(safeText,/serving size\s*([^\n]+)/i)); add('nutritionNotes','Calories',match(safeText,/calories\s*([0-9][^\n]*)/i)); }
  if(photoType==='Company / Contact Label'){ add('brand','Brand',match(safeText,/\bbrand\s*[:\-]\s*([^\n]+)/i)); add('parentCompany','Parent company / company wording',match(safeText,/\b(?:manufactured by|distributed by|imported by|licensed by|made for|packed for)\s*([^\n]+)/i)); add('countryMarket','Country / market',match(safeText,/\b(?:made in|product of)\s*([^\n]+)/i)); add('userNotes','Company relationship wording',safeText); }
  if(photoType==='Receipt Photo'){ add('storeLocation','Store / location',firstLine(safeText)); add('dateFound','Date found',match(safeText,/(\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b)/)); add('productName','Receipt product line',match(safeText,/\b([A-Z0-9][A-Z0-9 .'-]{3,})\s+\$?\d+\.\d{2}\b/)); add('upc','UPC visible on receipt',match(safeText,/\b(\d{8}|\d{12,14})\b/)); }
  return { suggestions, parserWarnings:warnings, phraseDetections, sanitizedText:safeText };
}
export function createOcrEvidenceDraft({ ocrResult, photoType, product={} }) { const text=ocrResult.correctedText || ocrResult.rawText || ''; return { evidenceTitle:`${photoType || 'Photo'} OCR draft${product.productName ? `: ${product.productName}` : ''}`, evidenceType: photoType==='Receipt Photo' ? 'Receipt/photo evidence' : photoType==='Other Evidence Photo' ? 'User upload' : 'Product label', sourceName: ocrResult.sourceType || ocrSourceForPhotoType(photoType), date:new Date().toISOString().slice(0,10), relatedProduct:product.productName || product.upc || '', relatedCompany:product.parentCompany || product.brand || '', claim:'User-captured label transcription draft', summary:`OCR text excerpt: ${text.slice(0,220)}`, quote:text, evidenceStatus:'Needs review', confidenceLevel: ocrResult.userReviewed ? 'Low' : 'Unknown', notes:`Photo imageId: ${ocrResult.imageId}; OCR confidence: ${ocrResult.confidence ?? 'unknown'}` }; }
export function compareLookupToLabel(product={}, suggestions=[]) { const fields=['productName','brand','ingredientsNotes','nutritionNotes','packagingLabels','countryMarket','parentCompany']; return fields.map((field)=>{ const ocr=suggestions.find(s=>s.field===field)?.value || ''; const existing=product[field] || ''; let status='Unable to compare'; if(existing&&ocr){ const a=existing.toLowerCase(), b=ocr.toLowerCase(); status=a===b?'Matches label':a.includes(b)?'Public database contains additional information':b.includes(a)?'Label contains additional information':'Possible conflict'; } else if(existing||ocr) status='Needs user review'; return { field, existing, labelValue:ocr, status }; }); }
